### ISSUE TITLE
🏡 Animation 💫

### ISSUE THREAD

**Issue by usama251993** [usamazansari/itinerary-assistant#53]
### Animation

> Implement Animation of cards on the home page

> Use `*.animation.ts`

Cards to appear from downwards fade to their original position and state

```css
/* Mock Transition */
mat-card {
  transition: translateY(10px);
  opacity: 0;
}
mat-card:animated {
  transition: translateY(0px);
  opacity: 1;
}
```
